update script
to install code deploy agent and start it

diff --git a/scripts/install_dependencies b/scripts/install_dependencies
--- a/scripts/install_dependencies
+++ b/scripts/install_dependencies
@@ -1,12 +1,7 @@
 #!/bin/bash
+
 apt-get update
 apt-get install -y apache2
-apt-get install -y ruby wget
-cd /home/ubuntu
-wget https://aws-codedeploy-us-east-1.s3.us-east1.amazonaws.com/latest/install
-chmod +x ./install
-./install auto
-service codedeploy-agent start
 apt-get install -y mysql-server
 apt-get install -y php-mysql
 apt-get install -y php libapache2-mod-php
@@ -21,3 +16,103 @@ cp dir.conf /etc/apache2/mods-enabled/dir.conf
 wget "https://s3-utility-vincentwijaya.s3.amazonaws.com/000-default.conf"
 cp 000-default.conf /etc/apache2/sites-available/000-default.conf
 systemctl restart apache2
+
+## Code Deploy Agent Bootstrap Script##
+
+
+exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
+AUTOUPDATE=false
+
+function installdep(){
+
+if [ ${PLAT} = "ubuntu" ]; then
+
+  apt-get -y update
+  # Satisfying even ubuntu older versions.
+  apt-get -y install jq awscli ruby2.0 || apt-get -y install jq awscli ruby
+
+
+
+elif [ ${PLAT} = "amz" ]; then
+  yum -y update
+  yum install -y aws-cli ruby jq
+
+fi
+
+}
+
+function platformize(){
+
+#Linux OS detection#
+ if hash lsb_release; then
+   echo "Ubuntu server OS detected"
+   export PLAT="ubuntu"
+
+
+elif hash yum; then
+  echo "Amazon Linux detected"
+  export PLAT="amz"
+
+ else
+   echo "Unsupported release"
+   exit 1
+
+ fi
+}
+
+
+function execute(){
+
+if [ ${PLAT} = "ubuntu" ]; then
+
+  cd /tmp/
+  wget https://aws-codedeploy-${REGION}.s3.amazonaws.com/latest/install
+  chmod +x ./install
+
+  if ./install auto; then
+    service codedeploy-agent start
+    echo "Instalation completed"
+      if ! ${AUTOUPDATE}; then
+            echo "Disabling Auto Update"
+            sed -i '/@reboot/d' /etc/cron.d/codedeploy-agent-update
+            chattr +i /etc/cron.d/codedeploy-agent-update
+            rm -f /tmp/install
+      fi
+    exit 0
+  else
+    echo "Instalation script failed, please investigate"
+    rm -f /tmp/install
+    exit 1
+  fi
+
+elif [ ${PLAT} = "amz" ]; then
+
+  cd /tmp/
+  wget https://aws-codedeploy-${REGION}.s3.amazonaws.com/latest/install
+  chmod +x ./install
+
+    if ./install auto; then
+      echo "Instalation completed"
+        if ! ${AUTOUPDATE}; then
+            echo "Disabling auto update"
+            sed -i '/@reboot/d' /etc/cron.d/codedeploy-agent-update
+            chattr +i /etc/cron.d/codedeploy-agent-update
+            rm -f /tmp/install
+        fi
+      exit 0
+    else
+      echo "Instalation script failed, please investigate"
+      rm -f /tmp/install
+      exit 1
+    fi
+
+else
+  echo "Unsupported platform ''${PLAT}''"
+fi
+
+}
+
+platformize
+installdep
+REGION=$(curl -s 169.254.169.254/latest/dynamic/instance-identity/document | jq -r ".region")
+execute
